# -*- coding: utf-8 -*-
"""CSE111 assignment 1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1q4bjqSe3h4RU0enZSrrgRc1BmM8dmAfp
"""

numNames = int(input('names >'))

nameDict = {'Fname':[],'Mname':[],'Lname':[]}

for i in range(numNames):
    names = input(f'name {i+1} > ').split(' ')

    if len(names) >= 1:
        nameDict["Fname"].append(names[0])

        if len(names) == 2:
            nameDict["Lname"].append(names[1])
        elif len(names) == 3:
            nameDict["Mname"].append(names[1])
            nameDict["Lname"].append(names[2])

print(nameDict)

#1
n= input('enter a name:')
upp=0
low=0
for i in n:
  if ord(i)>=65 and ord(i)<=90:
    upp+=1
  if ord(i)>=97 and ord(i)<=122:
    low+=1
if upp>low:
  print(n.upper())
else:
  print(n.lower())

#2
n=input()
integ=0
alph=0
for i in range(0,len(n)):
  if (ord(n[i])>=48 and ord(n[i])<=57):
    integ+=1
  elif ((ord(n[i])>=65 and ord(n[i])<=90) or (ord(n[i])>=97 and ord(n[i])<=120)):
    alph+=1
if (integ>0 and alph==0):
  print("NUMBER")
elif (alph>0 and integ==0):
  print('WORD')
elif (integ>0 and alph>0):
  print('MIXED')

#3
n= input()
ind1=0
ind2=0
for i in range(0,len(n)):
  if ord(n[i])>=65 and ord(n[i])<=90:
    ind1=i
    break
for i in range(ind1+1,len(n)):
  if ord(n[i])>=65 and ord(n[i])<=90:
    ind2=i
print(n[ind1+1:ind2])
if n[ind1+1:ind2]=="":
  print('BLANK')

#4
s1= input()
s2= input()
eps1=''
eps2=''
for i in s1:
  if i in s2:
    eps1+=i
for j in s2:
  if j in s1:
    eps2+=j
print(eps1+eps2)
if len(eps1+eps2)==0:
  print('nothing in common')

#5
n=input()
d=0
u=0
l=0
s=0

for i in range(len(n)):
  if n[i].isupper():
    u += 1
  elif n[i].islower():
    l += 1
  elif n[i].isdigit():
    n += 1
  else:
    s += 1
if d==0:
  print('Digit missing', end=', ')
if u==0:
  print('Uppercase missing', end=', ')
if l==0:
  print('Lowercase missing', end=', ')
if s==0:
  print('Special Missing', end='')
else:
  print('OK')

#list1
lst=[]
string=''
while string!='STOP':
  if string!='':
    lst.append(string)
  string=input("Enter the number: ")
n=0
final_list=[]
for n in lst:
  if n not in final_list:
    final_list.append(n)
final_list.sort()
for n in final_list:
  freq=lst.count(n)
  print(n,'-',freq,'times')

#list2
n= int(input())
m=0
ans=[]
for i in range (n):
  l=input().split()
  for i in range (len(l)):
    l[i]=int(l[i])
  sum=0
  for i in l:
    sum+=i
  if sum>m:
    m=sum
    ans=l
print(m,ans)

#list3
si = input()
list_1 = []
while si!="STOP":
  s = si.split(' ')

  for i in s:
    list_1.append(int(i))

  n = len(list_1)

  diff= [False] * n
  for i in range(0, n-1):
    d = abs(list_1[i]-list_1[i + 1])
  if (d == 0 or d > n-1 or diff[d] == True):
    print("Not UB Jumper")
  else:
    diff[d] == True
    print("UB Jumper")

#list3
inp=input()
ans_list=[]
while inp!='STOP':
   lst=inp.split(' ')
   mod_lst=[]
   for i in lst:
      mod_lst.append(int(i))
   sub_lst=[]
   for i in range(len(mod_lst)-1):
      sub=abs(mod_lst[i]-mod_lst[i+1])
      sub_lst.append(sub)

   lst2=[]
   for i in range(1,len(mod_lst)):
      lst2.append(i)
   flag=True
   for i in lst2:
      if i not in sub_lst:
         flag=False
      else:
         flag=True
   if flag:
      ans_list.append('UB Jumper')
   else:
      ans_list.append('Not UB Jumper')
   inp=input()
for i in ans_list:
   print(i)

#list4
list1=[]
n=int(input('Max number of participant: '))
k=int(input('max number of joins: '))
for i in range (0,n):
  a=int(input())
  if a+k<=5:
    list1.append(a)
b=len(a)//3:
print('Team members:',b)

#dictory1
dict_1 = {'a': 100, 'b': 100, 'c': 200, 'd': 300}
dict_2 = {'a': 300, 'b': 200, 'd': 400, 'e': 200}
dict_3 = {}
mylist = []

dict_3.update(dict_2)
dict_3.update(dict_1)

for i,j in dict_1.items():
  for x,y in dict_2.items():
    if i == x:
      dict_3[i]=(j+y)

print(dict_3)

for e in dict_3.values():
  if e not in mylist:
    mylist.append(e)

mylist.sort(reverse=False)
print('Values:',tuple(mylist))

#dictionary2
lst=[]
string=''
while string!='STOP':
  if string!='':
    lst.append(string)
  string=input("Enter the number: ")
output_dic={}
for n in lst:
  if n not in output_dic:
    output_dic[n]=1
  else:
    output_dic[n]+=1
for k in output_dic:
  print(k,'-',output_dic[k],'times')

#dictionary3
d= {}
list1 = input('Enter key and value: ').split(',')
for i in list1:
    temp = i.split(':')
    key = temp[1]
    val = temp[0]
    if key in d:
        d[key].append(val)
    else:
        d[key] = [val]
print(d)

#dictionary4
dict1={' ':0,'.':1,',':11,'?':111,'!':1111,':':11111,'A':2,'B':22,'C':222,'D':3,'E':33,'F':333,'G':4,'H':44,'I':444,'J':5,'K':55,'L':555,'M':6,'N':66, 'O':666, 'P':7, 'Q':77, 'R':777, 'S':7777, 'T':8, 'U':88, 'V':888, 'W':9, 'X':99, 'Y':999, 'Z':9999}
a=input()
for i in a:
  if i in dict1:
    print(dict1[i],end='')

#function1
def bmi(h,w):
  h=h/100
  BMI=w/(h**2)
  if BMI<=18.5:
    print("Score is",BMI,'.You are underweight')
  elif (BMI>=18.5 and BMI<=24.9):
    print("Score is",BMI,'.You are normal')
  elif (BMI>=25 and BMI<=30):
    print("Score is",BMI,'.You are overweight')
  elif (BMI>30):
    print("Score is",BMI,'.You are obese')
bmi(175,96)

#fun2
def sumDivisibles(min, max, div):
  sum = 0

  for i in range(min, max + 1):
    if (i % div == 0):
      sum += i
  return sum
min = int(input('Minimum: '))
max = int(input('Maximum: '))
div = int(input('Divisor: '))
print(sumDivisibles(min, max, div))

#function3
def fooddelivery(a,b):
  menu={'BBQ Chicken Cheese Burger':250,'Beef Burger':170,'Naga drums': 200}
  s=0
  for i in a:
    if i in menu:
      d= a[i]
      s+=d
  if b=='':
    s+=40
  else:
    s+=60
  c=(d*8)/100
  s+=c
  print('Your bill is: ',s)
fooddelivery('Beef Burger','Dhanmondi')